"""add hash for project

Revision ID: 0cd41610d1d0
Revises: 9d2df23c3be9
Create Date: 2021-02-04 17:52:24.594034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd41610d1d0'
down_revision = '9d2df23c3be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_hash')
    # ### end Alembic commands ###
