"""add latency for take

Revision ID: 2b65e1a82d22
Revises: 3fb5d6ff4cdb
Create Date: 2021-02-25 19:47:01.947524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '2b65e1a82d22'
down_revision = '3fb5d6ff4cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('take', sa.Column('latency', sa.Integer()))
    take = table('take', column('latency'))       
    op.execute(take.update().values(latency=0)) 
    op.alter_column('take', 'latency', nullable=False, server_default="0")    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('take', 'latency')
    # ### end Alembic commands ###
