"""add is_backing to track

Revision ID: 63cb3b652a1e
Revises: 3071621f99be
Create Date: 2021-02-05 12:55:50.250260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cb3b652a1e'
down_revision = '3071621f99be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('is_backing', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'is_backing')
    # ### end Alembic commands ###
