"""add datetime to take object

Revision ID: 9d2df23c3be9
Revises: b8047292e2fa
Create Date: 2021-01-27 13:04:00.851394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2df23c3be9'
down_revision = 'b8047292e2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('take', sa.Column('date_uploaded', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('take', 'date_uploaded')
    # ### end Alembic commands ###
