"""add latency_ms col for user

Revision ID: d94704805472
Revises: 2b65e1a82d22
Create Date: 2021-02-25 20:00:23.463790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94704805472'
down_revision = '2b65e1a82d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('take', sa.Column('latency_ms', sa.Integer(), nullable=False))
    op.drop_column('take', 'latency')
    op.add_column('user', sa.Column('latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'latency_ms')
    op.add_column('take', sa.Column('latency', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('take', 'latency_ms')
    # ### end Alembic commands ###
